//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Dirección { get; set; }
        public int IdGrupo { get; set; }
        public string Matricula { get; set; }
        public string NombreTutor { get; set; }
        public string Teléfono { get; set; }
        public string Correo { get; set; }
        public string Foto { get; set; }
    
        public virtual grupo grupo { get; set; }
    }
}
