//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apodo { get; set; }
        public string Password { get; set; }
        public string Privilegio { get; set; }
        public int IdEscuela { get; set; }
    
        public virtual escuela escuela { get; set; }
    }
}
